name: c_ri
description: "A revolutionary Point of Sale & inventory management application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'Emmanuel Sindani' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  android_intent: any # discontinued for security concerns
  android_intent_plus: ^5.0.2

  ## -- location services -- ##
  location: any
  geolocator: any
  geocoding: any
  

  permission_handler: ^11.3.1

  # -- utility packages
  timezone: any
  csv: any
  http: any
  intl: any
  logger: any
  lottie: any
  url_launcher: any
  connectivity_plus: any
  path_provider: any  
  flutter_native_splash: any
  image_picker: any
  flutter_typeahead: any
  country_picker: any
  gsheets: any
  googleapis: any

  # swipe/slideshow and indicator - onboardng packages
  liquid_swipe: any
  smooth_page_indicator: any


  # -- icon packages
  iconsax: any
  cupertino_icons: ^1.0.6

  # -- firebase packages
  firebase_app_check: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any
  firebase_storage: any

  # -- state management
  get: any
  universal_io: any
  get_storage: any
  shimmer: any
  
  # -- sqflite database storage
  sqflite: any
  sqflite_common_ffi: any

  # google fonts
  google_fonts: ^6.1.0
  
  
  loading_btn: ^1.0.3
  iconly: ^1.0.1
  cached_network_image: ^3.3.1

  # -- otp textfield package
  flutter_otp_text_field: any

  readmore: any
  carousel_slider: any
  flutter_rating_bar: any
  intl_phone_field: any
  path: any
  clock: any
  #currency_pickers: any
  country_code_picker: any
  #flutter_sim_country_code: any
  country_codes: any


  # -- scanners --
  barcode_scan2: any
  flutter_barcode_scanner: any
  #flutter_scanner_devxhub: ^1.0.2

  # -- charts --
  syncfusion_flutter_charts: any
  fl_chart: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # --- local assets --- #
  assets:
    - assets/currency_tings.csv
    - assets/icons/
    - assets/icons/flash_off.jpg
    - assets/icons/flash_on.jpeg
    - assets/icons/payment_methods/
    - assets/icons/switch_camera.png
    - assets/images/
    - assets/images/animations/  
    - assets/images/lottie_anime/
    - assets/images/lottie_anime/loader_2.gif
    - assets/images/on_boarding_images/
    - assets/images/profile/
    - assets/images/logos/
    
    

  # --- local fonts --- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic 
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
